### ISSUE TITLE
How can we draw multiple branches from the same node?

### ISSUE THREAD

**Issue by madmanblues** [uonun/UDNZTimeline#2]
Hi, 

I really like this plugin, I want to know (or suggest as improvement). Is it possible to have multiple branches starting from the same node?

Many thanks and kind regards

**Comment by uonun** [comment]
Hi, I am glad it is useful to you, it is ready for multiple branches now, enjoy it. Keep letting me know if any questions pls, thanks.

**Comment by uonun** [comment]
Did you set the height(`option.container.height`) of the container at the beginning?
Or you can change it in the jQuery way like this: `$("#TimelineJS_934871981").attr("height",300)`.

Sorry that it is not supported dynamically adding/removing nodes at the runtime at the present.
